# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bloodbank
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# For JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# For HikariCP
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10


# Enable Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
