# MySQL Configuration
spring.datasource.url=jdbc:mysql://srv2108.hstgr.io:3306/u567114702_bloodbank?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u567114702_root
spring.datasource.password=Sj@bloodflow7113


#spring.datasource.url=jdbc:mysql://localhost:3306/bloodbank
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework=DEBUG
server.address=0.0.0.0
server.port=8090
server.ssl.enabled=false



# For JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# For HikariCP
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10


# Enable Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sourabh.jadhav.job@gmail.com
spring.mail.password=wojd oxfn snso ypfs


# Additional Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
